name: our first pratcice
on: workflow_dispatch
jobs:
  first_job:
   runs-on: ubuntu-latest
   steps:
   - name: print greeting
     run: echo "Hi Good Morning"
   - name: print end of day
     run: echo "Im off for the day, BYE!!"
